/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as plokyResolverSol from "./PlokyResolver.sol";
export { PlokyResolverLite__factory } from "./PlokyResolverLite__factory";
export { PlokyToken__factory } from "./PlokyToken__factory";
