/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPlokyToken__factory } from "./IPlokyToken__factory";
export { IUMAOptimisticOracle__factory } from "./IUMAOptimisticOracle__factory";
export { PlokyResolver__factory } from "./PlokyResolver__factory";
