/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as plokyResolverSol from "./PlokyResolver.sol";
export type { plokyResolverSol };
export type { PlokyResolverLite } from "./PlokyResolverLite";
export type { PlokyToken } from "./PlokyToken";
