/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PlokyResolverLite {
  export type DisputeStruct = {
    disputer: AddressLike;
    reason: string;
    evidenceCID: BytesLike;
    bondAmount: BigNumberish;
    resolved: boolean;
    bondReturned: boolean;
  };

  export type DisputeStructOutput = [
    disputer: string,
    reason: string,
    evidenceCID: string,
    bondAmount: bigint,
    resolved: boolean,
    bondReturned: boolean
  ] & {
    disputer: string;
    reason: string;
    evidenceCID: string;
    bondAmount: bigint;
    resolved: boolean;
    bondReturned: boolean;
  };
}

export interface PlokyResolverLiteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AI_ORACLE_ROLE"
      | "ARBITER_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "DISPUTE_BOND"
      | "RESOLVER_ROLE"
      | "STAKE_MIN"
      | "VERDICT_BOND"
      | "approveVerdict"
      | "cancelQuestion"
      | "createQuestion"
      | "disputes"
      | "executeVerdict"
      | "getAllIds"
      | "getDisputes"
      | "getQuestionCount"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "plkyToken"
      | "proposals"
      | "proposeVerdict"
      | "questionIds"
      | "questions"
      | "quorum"
      | "raiseDispute"
      | "renounceRole"
      | "resolveDispute"
      | "revokeRole"
      | "stake"
      | "stakes"
      | "submitAIAnalysis"
      | "submitEvidence"
      | "supportsInterface"
      | "unstake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIAnalysis"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EvidenceSubmitted"
      | "QuestionCancelled"
      | "QuestionCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Staked"
      | "Unstaked"
      | "VerdictApproved"
      | "VerdictExecuted"
      | "VerdictProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "AI_ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLVER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "STAKE_MIN", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VERDICT_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "approveVerdict",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelQuestion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createQuestion",
    values: [string, BytesLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeVerdict",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAllIds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDisputes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "plkyToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVerdict",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "questionIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "questions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "quorum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "stake", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "submitAIAnalysis",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "AI_ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLVER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "STAKE_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VERDICT_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuestionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plkyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "questionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "questions", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitAIAnalysis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
}

export namespace AIAnalysisEvent {
  export type InputTuple = [
    qId: BytesLike,
    confidence: BigNumberish,
    outcome: BigNumberish
  ];
  export type OutputTuple = [qId: string, confidence: bigint, outcome: bigint];
  export interface OutputObject {
    qId: string;
    confidence: bigint;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    qId: BytesLike,
    idx: BigNumberish,
    disputer: AddressLike
  ];
  export type OutputTuple = [qId: string, idx: bigint, disputer: string];
  export interface OutputObject {
    qId: string;
    idx: bigint;
    disputer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    qId: BytesLike,
    idx: BigNumberish,
    accepted: boolean
  ];
  export type OutputTuple = [qId: string, idx: bigint, accepted: boolean];
  export interface OutputObject {
    qId: string;
    idx: bigint;
    accepted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    qId: BytesLike,
    submitter: AddressLike,
    cid: BytesLike,
    etype: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    submitter: string,
    cid: string,
    etype: bigint
  ];
  export interface OutputObject {
    qId: string;
    submitter: string;
    cid: string;
    etype: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionCancelledEvent {
  export type InputTuple = [id: BytesLike, by: AddressLike];
  export type OutputTuple = [id: string, by: string];
  export interface OutputObject {
    id: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    title: string,
    creator: AddressLike,
    time: BigNumberish,
    category: string,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    title: string,
    creator: string,
    time: bigint,
    category: string,
    tier: bigint
  ];
  export interface OutputObject {
    id: string;
    title: string;
    creator: string;
    time: bigint;
    category: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakedEvent {
  export type InputTuple = [resolver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [resolver: string, amount: bigint];
  export interface OutputObject {
    resolver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakedEvent {
  export type InputTuple = [resolver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [resolver: string, amount: bigint];
  export interface OutputObject {
    resolver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictApprovedEvent {
  export type InputTuple = [
    qId: BytesLike,
    pid: BytesLike,
    approver: AddressLike
  ];
  export type OutputTuple = [qId: string, pid: string, approver: string];
  export interface OutputObject {
    qId: string;
    pid: string;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictExecutedEvent {
  export type InputTuple = [
    qId: BytesLike,
    outcome: BigNumberish,
    executor: AddressLike
  ];
  export type OutputTuple = [qId: string, outcome: bigint, executor: string];
  export interface OutputObject {
    qId: string;
    outcome: bigint;
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictProposedEvent {
  export type InputTuple = [
    qId: BytesLike,
    pid: BytesLike,
    outcome: BigNumberish,
    proposer: AddressLike
  ];
  export type OutputTuple = [
    qId: string,
    pid: string,
    outcome: bigint,
    proposer: string
  ];
  export interface OutputObject {
    qId: string;
    pid: string;
    outcome: bigint;
    proposer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlokyResolverLite extends BaseContract {
  connect(runner?: ContractRunner | null): PlokyResolverLite;
  waitForDeployment(): Promise<this>;

  interface: PlokyResolverLiteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AI_ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  ARBITER_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DISPUTE_BOND: TypedContractMethod<[], [bigint], "view">;

  RESOLVER_ROLE: TypedContractMethod<[], [string], "view">;

  STAKE_MIN: TypedContractMethod<[], [bigint], "view">;

  VERDICT_BOND: TypedContractMethod<[], [bigint], "view">;

  approveVerdict: TypedContractMethod<
    [qId: BytesLike, pid: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelQuestion: TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;

  createQuestion: TypedContractMethod<
    [
      title: string,
      evidenceCID: BytesLike,
      category: string,
      resolutionTime: BigNumberish,
      tier: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  disputes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, boolean, boolean] & {
        disputer: string;
        reason: string;
        evidenceCID: string;
        bondAmount: bigint;
        resolved: boolean;
        bondReturned: boolean;
      }
    ],
    "view"
  >;

  executeVerdict: TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;

  getAllIds: TypedContractMethod<[], [string[]], "view">;

  getDisputes: TypedContractMethod<
    [qId: BytesLike],
    [PlokyResolverLite.DisputeStructOutput[]],
    "view"
  >;

  getQuestionCount: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  plkyToken: TypedContractMethod<[], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, bigint, boolean, string] & {
        outcome: bigint;
        reasonCID: string;
        approvals: bigint;
        required: bigint;
        timelockUntil: bigint;
        executed: boolean;
        proposer: string;
      }
    ],
    "view"
  >;

  proposeVerdict: TypedContractMethod<
    [qId: BytesLike, outcome: BigNumberish, reasonCID: BytesLike],
    [void],
    "nonpayable"
  >;

  questionIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  questions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        bigint,
        bigint
      ] & {
        title: string;
        evidenceCID: string;
        resolutionTime: bigint;
        status: bigint;
        outcome: bigint;
        tier: bigint;
        disputeCount: bigint;
        isFrozen: boolean;
        resolvedBy: string;
        activeProposalId: string;
        aiConfidence: bigint;
        aiOutcome: bigint;
      }
    ],
    "view"
  >;

  quorum: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [qId: BytesLike, reason: string, evidenceCID: BytesLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [qId: BytesLike, idx: BigNumberish, accept: boolean],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  stakes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  submitAIAnalysis: TypedContractMethod<
    [qId: BytesLike, confidence: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [qId: BytesLike, cid: BytesLike, etype: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unstake: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AI_ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ARBITER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLVER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STAKE_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERDICT_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "approveVerdict"
  ): TypedContractMethod<
    [qId: BytesLike, pid: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelQuestion"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createQuestion"
  ): TypedContractMethod<
    [
      title: string,
      evidenceCID: BytesLike,
      category: string,
      resolutionTime: BigNumberish,
      tier: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, boolean, boolean] & {
        disputer: string;
        reason: string;
        evidenceCID: string;
        bondAmount: bigint;
        resolved: boolean;
        bondReturned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeVerdict"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDisputes"
  ): TypedContractMethod<
    [qId: BytesLike],
    [PlokyResolverLite.DisputeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQuestionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "plkyToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, bigint, boolean, string] & {
        outcome: bigint;
        reasonCID: string;
        approvals: bigint;
        required: bigint;
        timelockUntil: bigint;
        executed: boolean;
        proposer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeVerdict"
  ): TypedContractMethod<
    [qId: BytesLike, outcome: BigNumberish, reasonCID: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "questionIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "questions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string,
        string,
        bigint,
        bigint
      ] & {
        title: string;
        evidenceCID: string;
        resolutionTime: bigint;
        status: bigint;
        outcome: bigint;
        tier: bigint;
        disputeCount: bigint;
        isFrozen: boolean;
        resolvedBy: string;
        activeProposalId: string;
        aiConfidence: bigint;
        aiOutcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [qId: BytesLike, reason: string, evidenceCID: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [qId: BytesLike, idx: BigNumberish, accept: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitAIAnalysis"
  ): TypedContractMethod<
    [qId: BytesLike, confidence: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [qId: BytesLike, cid: BytesLike, etype: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "AIAnalysis"
  ): TypedContractEvent<
    AIAnalysisEvent.InputTuple,
    AIAnalysisEvent.OutputTuple,
    AIAnalysisEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuestionCancelled"
  ): TypedContractEvent<
    QuestionCancelledEvent.InputTuple,
    QuestionCancelledEvent.OutputTuple,
    QuestionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "QuestionCreated"
  ): TypedContractEvent<
    QuestionCreatedEvent.InputTuple,
    QuestionCreatedEvent.OutputTuple,
    QuestionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Staked"
  ): TypedContractEvent<
    StakedEvent.InputTuple,
    StakedEvent.OutputTuple,
    StakedEvent.OutputObject
  >;
  getEvent(
    key: "Unstaked"
  ): TypedContractEvent<
    UnstakedEvent.InputTuple,
    UnstakedEvent.OutputTuple,
    UnstakedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictApproved"
  ): TypedContractEvent<
    VerdictApprovedEvent.InputTuple,
    VerdictApprovedEvent.OutputTuple,
    VerdictApprovedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictExecuted"
  ): TypedContractEvent<
    VerdictExecutedEvent.InputTuple,
    VerdictExecutedEvent.OutputTuple,
    VerdictExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictProposed"
  ): TypedContractEvent<
    VerdictProposedEvent.InputTuple,
    VerdictProposedEvent.OutputTuple,
    VerdictProposedEvent.OutputObject
  >;

  filters: {
    "AIAnalysis(bytes32,uint256,uint8)": TypedContractEvent<
      AIAnalysisEvent.InputTuple,
      AIAnalysisEvent.OutputTuple,
      AIAnalysisEvent.OutputObject
    >;
    AIAnalysis: TypedContractEvent<
      AIAnalysisEvent.InputTuple,
      AIAnalysisEvent.OutputTuple,
      AIAnalysisEvent.OutputObject
    >;

    "DisputeRaised(bytes32,uint256,address)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint256,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EvidenceSubmitted(bytes32,address,bytes32,uint8)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "QuestionCancelled(bytes32,address)": TypedContractEvent<
      QuestionCancelledEvent.InputTuple,
      QuestionCancelledEvent.OutputTuple,
      QuestionCancelledEvent.OutputObject
    >;
    QuestionCancelled: TypedContractEvent<
      QuestionCancelledEvent.InputTuple,
      QuestionCancelledEvent.OutputTuple,
      QuestionCancelledEvent.OutputObject
    >;

    "QuestionCreated(bytes32,string,address,uint256,string,uint8)": TypedContractEvent<
      QuestionCreatedEvent.InputTuple,
      QuestionCreatedEvent.OutputTuple,
      QuestionCreatedEvent.OutputObject
    >;
    QuestionCreated: TypedContractEvent<
      QuestionCreatedEvent.InputTuple,
      QuestionCreatedEvent.OutputTuple,
      QuestionCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Staked(address,uint256)": TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;
    Staked: TypedContractEvent<
      StakedEvent.InputTuple,
      StakedEvent.OutputTuple,
      StakedEvent.OutputObject
    >;

    "Unstaked(address,uint256)": TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;
    Unstaked: TypedContractEvent<
      UnstakedEvent.InputTuple,
      UnstakedEvent.OutputTuple,
      UnstakedEvent.OutputObject
    >;

    "VerdictApproved(bytes32,bytes32,address)": TypedContractEvent<
      VerdictApprovedEvent.InputTuple,
      VerdictApprovedEvent.OutputTuple,
      VerdictApprovedEvent.OutputObject
    >;
    VerdictApproved: TypedContractEvent<
      VerdictApprovedEvent.InputTuple,
      VerdictApprovedEvent.OutputTuple,
      VerdictApprovedEvent.OutputObject
    >;

    "VerdictExecuted(bytes32,uint8,address)": TypedContractEvent<
      VerdictExecutedEvent.InputTuple,
      VerdictExecutedEvent.OutputTuple,
      VerdictExecutedEvent.OutputObject
    >;
    VerdictExecuted: TypedContractEvent<
      VerdictExecutedEvent.InputTuple,
      VerdictExecutedEvent.OutputTuple,
      VerdictExecutedEvent.OutputObject
    >;

    "VerdictProposed(bytes32,bytes32,uint8,address)": TypedContractEvent<
      VerdictProposedEvent.InputTuple,
      VerdictProposedEvent.OutputTuple,
      VerdictProposedEvent.OutputObject
    >;
    VerdictProposed: TypedContractEvent<
      VerdictProposedEvent.InputTuple,
      VerdictProposedEvent.OutputTuple,
      VerdictProposedEvent.OutputObject
    >;
  };
}
