/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IPlokyToken } from "./IPlokyToken";
export type { IUMAOptimisticOracle } from "./IUMAOptimisticOracle";
export type { PlokyResolver } from "./PlokyResolver";
