/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace PlokyResolver {
  export type AIAnalysisStruct = {
    questionId: BytesLike;
    confidenceScore: BigNumberish;
    recommendedOutcome: BigNumberish;
    analysisCID: string;
    timestamp: BigNumberish;
    aiModelVersion: string;
    sentimentScore: BigNumberish;
    factCheckScore: BigNumberish;
    biasScore: BigNumberish;
  };

  export type AIAnalysisStructOutput = [
    questionId: string,
    confidenceScore: bigint,
    recommendedOutcome: bigint,
    analysisCID: string,
    timestamp: bigint,
    aiModelVersion: string,
    sentimentScore: bigint,
    factCheckScore: bigint,
    biasScore: bigint
  ] & {
    questionId: string;
    confidenceScore: bigint;
    recommendedOutcome: bigint;
    analysisCID: string;
    timestamp: bigint;
    aiModelVersion: string;
    sentimentScore: bigint;
    factCheckScore: bigint;
    biasScore: bigint;
  };

  export type DisputeStruct = {
    questionId: BytesLike;
    disputer: AddressLike;
    reason: string;
    evidenceCID: string;
    timestamp: BigNumberish;
    resolved: boolean;
    resolution: string;
    bondAmount: BigNumberish;
    bondReturned: boolean;
    disputeIndex: BigNumberish;
  };

  export type DisputeStructOutput = [
    questionId: string,
    disputer: string,
    reason: string,
    evidenceCID: string,
    timestamp: bigint,
    resolved: boolean,
    resolution: string,
    bondAmount: bigint,
    bondReturned: boolean,
    disputeIndex: bigint
  ] & {
    questionId: string;
    disputer: string;
    reason: string;
    evidenceCID: string;
    timestamp: bigint;
    resolved: boolean;
    resolution: string;
    bondAmount: bigint;
    bondReturned: boolean;
    disputeIndex: bigint;
  };

  export type EvidenceStruct = {
    ipfsCID: string;
    description: string;
    submitter: AddressLike;
    timestamp: BigNumberish;
    evidenceType: BigNumberish;
    bondAmount: BigNumberish;
    bondReturned: boolean;
  };

  export type EvidenceStructOutput = [
    ipfsCID: string,
    description: string,
    submitter: string,
    timestamp: bigint,
    evidenceType: bigint,
    bondAmount: bigint,
    bondReturned: boolean
  ] & {
    ipfsCID: string;
    description: string;
    submitter: string;
    timestamp: bigint;
    evidenceType: bigint;
    bondAmount: bigint;
    bondReturned: boolean;
  };

  export type QuestionStruct = {
    id: BytesLike;
    title: string;
    descriptionCID: string;
    category: string;
    createdAt: BigNumberish;
    deadline: BigNumberish;
    creator: AddressLike;
    status: BigNumberish;
    outcome: BigNumberish;
    verdictCID: string;
    verdictSummary: string;
    resolvedAt: BigNumberish;
    resolvedBy: AddressLike;
    disputeCount: BigNumberish;
    frozen: boolean;
    activeProposalId: BytesLike;
    tier: BigNumberish;
    currentStep: BigNumberish;
    aiConfidenceScore: BigNumberish;
    aiAnalysisCID: string;
  };

  export type QuestionStructOutput = [
    id: string,
    title: string,
    descriptionCID: string,
    category: string,
    createdAt: bigint,
    deadline: bigint,
    creator: string,
    status: bigint,
    outcome: bigint,
    verdictCID: string,
    verdictSummary: string,
    resolvedAt: bigint,
    resolvedBy: string,
    disputeCount: bigint,
    frozen: boolean,
    activeProposalId: string,
    tier: bigint,
    currentStep: bigint,
    aiConfidenceScore: bigint,
    aiAnalysisCID: string
  ] & {
    id: string;
    title: string;
    descriptionCID: string;
    category: string;
    createdAt: bigint;
    deadline: bigint;
    creator: string;
    status: bigint;
    outcome: bigint;
    verdictCID: string;
    verdictSummary: string;
    resolvedAt: bigint;
    resolvedBy: string;
    disputeCount: bigint;
    frozen: boolean;
    activeProposalId: string;
    tier: bigint;
    currentStep: bigint;
    aiConfidenceScore: bigint;
    aiAnalysisCID: string;
  };

  export type ResolverProfileStruct = {
    reputationScore: BigNumberish;
    totalResolved: BigNumberish;
    correctResolutions: BigNumberish;
    stakedAmount: BigNumberish;
    slashCount: BigNumberish;
    isActive: boolean;
    joinTimestamp: BigNumberish;
    lastActivityTimestamp: BigNumberish;
  };

  export type ResolverProfileStructOutput = [
    reputationScore: bigint,
    totalResolved: bigint,
    correctResolutions: bigint,
    stakedAmount: bigint,
    slashCount: bigint,
    isActive: boolean,
    joinTimestamp: bigint,
    lastActivityTimestamp: bigint
  ] & {
    reputationScore: bigint;
    totalResolved: bigint;
    correctResolutions: bigint;
    stakedAmount: bigint;
    slashCount: bigint;
    isActive: boolean;
    joinTimestamp: bigint;
    lastActivityTimestamp: bigint;
  };
}

export interface PlokyResolverInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "AI_ORACLE_ROLE"
      | "ARBITER_ROLE"
      | "AUTO_FREEZE_THRESHOLD"
      | "DEFAULT_ADMIN_ROLE"
      | "DISPUTE_BOND"
      | "DISPUTE_WINDOW"
      | "EVIDENCE_BOND"
      | "MAX_REPUTATION"
      | "MIN_EVIDENCE"
      | "MIN_RESOLVER_STAKE"
      | "RESOLVER_ROLE"
      | "SLASH_PENALTY"
      | "TIMELOCK_PERIOD"
      | "VERDICT_BOND"
      | "VERSION"
      | "YES_OR_NO_IDENTIFIER"
      | "aiAnalyses"
      | "aiConfidenceThreshold"
      | "allIds"
      | "approveVerdict"
      | "cancelQuestion"
      | "castCommunityVote"
      | "communityVotes"
      | "createQuestion"
      | "disputes"
      | "emergencyPause"
      | "emergencyUnpause"
      | "enableUMA"
      | "evidence"
      | "executeVerdict"
      | "finalizeCommunityVote"
      | "freezeQuestion"
      | "getAIAnalysis"
      | "getAllIds"
      | "getDisputes"
      | "getEvidence"
      | "getProposal"
      | "getProposalWeight"
      | "getQuestion"
      | "getResolver"
      | "getResolverWeight"
      | "getRoleAdmin"
      | "grantRole"
      | "hasApproved"
      | "hasDisputed"
      | "hasRole"
      | "hasVoted"
      | "paused"
      | "plkyToken"
      | "proposals"
      | "proposeVerdict"
      | "questions"
      | "quorumThreshold"
      | "raiseDispute"
      | "renounceRole"
      | "requestUMAResolution"
      | "resolveDispute"
      | "resolverCount"
      | "resolverList"
      | "resolvers"
      | "revokeRole"
      | "setAIThreshold"
      | "setQuorum"
      | "setTreasury"
      | "settleUMAResolution"
      | "slashResolver"
      | "stakeAsResolver"
      | "submitAIAnalysis"
      | "submitEvidence"
      | "supportsInterface"
      | "totalQuestions"
      | "treasury"
      | "umaEnabled"
      | "umaOracle"
      | "unfreezeQuestion"
      | "unstakeAsResolver"
      | "withdrawStuckTokens"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIAnalysisSubmitted"
      | "BondReturned"
      | "BondSeized"
      | "CommunityVoteFinalized"
      | "CommunityVoted"
      | "DisputeRaised"
      | "DisputeResolved"
      | "EscalationAdvanced"
      | "EvidenceSubmitted"
      | "Paused"
      | "QuestionCancelled"
      | "QuestionCreated"
      | "QuestionFrozen"
      | "QuestionUnfrozen"
      | "QuorumChanged"
      | "ResolverAdded"
      | "ResolverRemoved"
      | "ResolverSlashed"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "UMAEnabled"
      | "UMARequested"
      | "Unpaused"
      | "VerdictApproved"
      | "VerdictExecuted"
      | "VerdictProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AI_ORACLE_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ARBITER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "AUTO_FREEZE_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DISPUTE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "EVIDENCE_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_REPUTATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_EVIDENCE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_RESOLVER_STAKE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RESOLVER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SLASH_PENALTY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TIMELOCK_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERDICT_BOND",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "YES_OR_NO_IDENTIFIER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aiAnalyses",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "aiConfidenceThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveVerdict",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelQuestion",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "castCommunityVote",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "communityVotes",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createQuestion",
    values: [string, string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyPause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyUnpause",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableUMA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "evidence",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeVerdict",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeCommunityVote",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "freezeQuestion",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAIAnalysis",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getAllIds", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getDisputes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvidence",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalWeight",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuestion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getResolverWeight",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasApproved",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasDisputed",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "plkyToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVerdict",
    values: [BytesLike, BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "questions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "quorumThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [BytesLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUMAResolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [BytesLike, BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "resolverCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resolverList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resolvers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAIThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleUMAResolution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "slashResolver",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAsResolver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAIAnalysis",
    values: [
      BytesLike,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEvidence",
    values: [BytesLike, string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalQuestions",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "umaEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "umaOracle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unfreezeQuestion",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeAsResolver",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawStuckTokens",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "AI_ORACLE_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ARBITER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "AUTO_FREEZE_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DISPUTE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "EVIDENCE_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_REPUTATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_EVIDENCE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_RESOLVER_STAKE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RESOLVER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SLASH_PENALTY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TIMELOCK_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERDICT_BOND",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "YES_OR_NO_IDENTIFIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "aiAnalyses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "aiConfidenceThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "castCommunityVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "communityVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "disputes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyPause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyUnpause",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "enableUMA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "evidence", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeCommunityVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezeQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAIAnalysis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAllIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDisputes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolverWeight",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hasApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasDisputed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plkyToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeVerdict",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "questions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quorumThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUMAResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolverList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolvers", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAIThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setQuorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleUMAResolution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slashResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeAsResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAIAnalysis",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEvidence",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalQuestions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "umaEnabled", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "umaOracle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unfreezeQuestion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeAsResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawStuckTokens",
    data: BytesLike
  ): Result;
}

export namespace AIAnalysisSubmittedEvent {
  export type InputTuple = [
    qId: BytesLike,
    confidence: BigNumberish,
    recommended: BigNumberish,
    cid: string
  ];
  export type OutputTuple = [
    qId: string,
    confidence: bigint,
    recommended: bigint,
    cid: string
  ];
  export interface OutputObject {
    qId: string;
    confidence: bigint;
    recommended: bigint;
    cid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondReturnedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, amount: bigint, reason: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BondSeizedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [user: string, amount: bigint, reason: string];
  export interface OutputObject {
    user: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommunityVoteFinalizedEvent {
  export type InputTuple = [
    qId: BytesLike,
    outcome: BigNumberish,
    yesWeight: BigNumberish,
    noWeight: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    outcome: bigint,
    yesWeight: bigint,
    noWeight: bigint
  ];
  export interface OutputObject {
    qId: string;
    outcome: bigint;
    yesWeight: bigint;
    noWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CommunityVotedEvent {
  export type InputTuple = [
    qId: BytesLike,
    voter: AddressLike,
    weight: BigNumberish,
    vote: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    voter: string,
    weight: bigint,
    vote: bigint
  ];
  export interface OutputObject {
    qId: string;
    voter: string;
    weight: bigint;
    vote: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeRaisedEvent {
  export type InputTuple = [
    qId: BytesLike,
    disputer: AddressLike,
    reason: string,
    cid: string,
    bond: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    disputer: string,
    reason: string,
    cid: string,
    bond: bigint
  ];
  export interface OutputObject {
    qId: string;
    disputer: string;
    reason: string;
    cid: string;
    bond: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DisputeResolvedEvent {
  export type InputTuple = [
    qId: BytesLike,
    index: BigNumberish,
    resolution: string,
    bondReturned: boolean
  ];
  export type OutputTuple = [
    qId: string,
    index: bigint,
    resolution: string,
    bondReturned: boolean
  ];
  export interface OutputObject {
    qId: string;
    index: bigint;
    resolution: string;
    bondReturned: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EscalationAdvancedEvent {
  export type InputTuple = [
    qId: BytesLike,
    fromStep: BigNumberish,
    toStep: BigNumberish
  ];
  export type OutputTuple = [qId: string, fromStep: bigint, toStep: bigint];
  export interface OutputObject {
    qId: string;
    fromStep: bigint;
    toStep: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EvidenceSubmittedEvent {
  export type InputTuple = [
    qId: BytesLike,
    submitter: AddressLike,
    cid: string,
    t: BigNumberish,
    bond: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    submitter: string,
    cid: string,
    t: bigint,
    bond: bigint
  ];
  export interface OutputObject {
    qId: string;
    submitter: string;
    cid: string;
    t: bigint;
    bond: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionCancelledEvent {
  export type InputTuple = [qId: BytesLike, reason: string];
  export type OutputTuple = [qId: string, reason: string];
  export interface OutputObject {
    qId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionCreatedEvent {
  export type InputTuple = [
    id: BytesLike,
    title: string,
    creator: AddressLike,
    deadline: BigNumberish,
    descCID: string,
    tier: BigNumberish
  ];
  export type OutputTuple = [
    id: string,
    title: string,
    creator: string,
    deadline: bigint,
    descCID: string,
    tier: bigint
  ];
  export interface OutputObject {
    id: string;
    title: string;
    creator: string;
    deadline: bigint;
    descCID: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionFrozenEvent {
  export type InputTuple = [qId: BytesLike, by: AddressLike, reason: string];
  export type OutputTuple = [qId: string, by: string, reason: string];
  export interface OutputObject {
    qId: string;
    by: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuestionUnfrozenEvent {
  export type InputTuple = [qId: BytesLike, by: AddressLike];
  export type OutputTuple = [qId: string, by: string];
  export interface OutputObject {
    qId: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuorumChangedEvent {
  export type InputTuple = [
    old_: BigNumberish,
    new_: BigNumberish,
    by: AddressLike
  ];
  export type OutputTuple = [old_: bigint, new_: bigint, by: string];
  export interface OutputObject {
    old_: bigint;
    new_: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverAddedEvent {
  export type InputTuple = [
    r: AddressLike,
    stake: BigNumberish,
    by: AddressLike
  ];
  export type OutputTuple = [r: string, stake: bigint, by: string];
  export interface OutputObject {
    r: string;
    stake: bigint;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverRemovedEvent {
  export type InputTuple = [r: AddressLike, by: AddressLike];
  export type OutputTuple = [r: string, by: string];
  export interface OutputObject {
    r: string;
    by: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ResolverSlashedEvent {
  export type InputTuple = [
    r: AddressLike,
    amount: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [r: string, amount: bigint, reason: string];
  export interface OutputObject {
    r: string;
    amount: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UMAEnabledEvent {
  export type InputTuple = [oracle: AddressLike];
  export type OutputTuple = [oracle: string];
  export interface OutputObject {
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UMARequestedEvent {
  export type InputTuple = [
    qId: BytesLike,
    identifier: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    identifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    qId: string;
    identifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictApprovedEvent {
  export type InputTuple = [
    qId: BytesLike,
    pid: BytesLike,
    approver: AddressLike,
    count: BigNumberish,
    weight: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    pid: string,
    approver: string,
    count: bigint,
    weight: bigint
  ];
  export interface OutputObject {
    qId: string;
    pid: string;
    approver: string;
    count: bigint;
    weight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictExecutedEvent {
  export type InputTuple = [
    qId: BytesLike,
    outcome: BigNumberish,
    verdictCID: string,
    executor: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    outcome: bigint,
    verdictCID: string,
    executor: string,
    ts: bigint
  ];
  export interface OutputObject {
    qId: string;
    outcome: bigint;
    verdictCID: string;
    executor: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerdictProposedEvent {
  export type InputTuple = [
    qId: BytesLike,
    pid: BytesLike,
    outcome: BigNumberish,
    proposer: AddressLike,
    reasonCID: string,
    timelockEnds: BigNumberish
  ];
  export type OutputTuple = [
    qId: string,
    pid: string,
    outcome: bigint,
    proposer: string,
    reasonCID: string,
    timelockEnds: bigint
  ];
  export interface OutputObject {
    qId: string;
    pid: string;
    outcome: bigint;
    proposer: string;
    reasonCID: string;
    timelockEnds: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PlokyResolver extends BaseContract {
  connect(runner?: ContractRunner | null): PlokyResolver;
  waitForDeployment(): Promise<this>;

  interface: PlokyResolverInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  AI_ORACLE_ROLE: TypedContractMethod<[], [string], "view">;

  ARBITER_ROLE: TypedContractMethod<[], [string], "view">;

  AUTO_FREEZE_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DISPUTE_BOND: TypedContractMethod<[], [bigint], "view">;

  DISPUTE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  EVIDENCE_BOND: TypedContractMethod<[], [bigint], "view">;

  MAX_REPUTATION: TypedContractMethod<[], [bigint], "view">;

  MIN_EVIDENCE: TypedContractMethod<[], [bigint], "view">;

  MIN_RESOLVER_STAKE: TypedContractMethod<[], [bigint], "view">;

  RESOLVER_ROLE: TypedContractMethod<[], [string], "view">;

  SLASH_PENALTY: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK_PERIOD: TypedContractMethod<[], [bigint], "view">;

  VERDICT_BOND: TypedContractMethod<[], [bigint], "view">;

  VERSION: TypedContractMethod<[], [bigint], "view">;

  YES_OR_NO_IDENTIFIER: TypedContractMethod<[], [string], "view">;

  aiAnalyses: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        questionId: string;
        confidenceScore: bigint;
        recommendedOutcome: bigint;
        analysisCID: string;
        timestamp: bigint;
        aiModelVersion: string;
        sentimentScore: bigint;
        factCheckScore: bigint;
        biasScore: bigint;
      }
    ],
    "view"
  >;

  aiConfidenceThreshold: TypedContractMethod<[], [bigint], "view">;

  allIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approveVerdict: TypedContractMethod<
    [qId: BytesLike, pid: BytesLike],
    [void],
    "nonpayable"
  >;

  cancelQuestion: TypedContractMethod<
    [qId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  castCommunityVote: TypedContractMethod<
    [qId: BytesLike, vote: BigNumberish],
    [void],
    "nonpayable"
  >;

  communityVotes: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  createQuestion: TypedContractMethod<
    [
      title: string,
      descCID: string,
      category: string,
      deadline: BigNumberish,
      tier: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  disputes: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        questionId: string;
        disputer: string;
        reason: string;
        evidenceCID: string;
        timestamp: bigint;
        resolved: boolean;
        resolution: string;
        bondAmount: bigint;
        bondReturned: boolean;
        disputeIndex: bigint;
      }
    ],
    "view"
  >;

  emergencyPause: TypedContractMethod<[], [void], "nonpayable">;

  emergencyUnpause: TypedContractMethod<[], [void], "nonpayable">;

  enableUMA: TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;

  evidence: TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        ipfsCID: string;
        description: string;
        submitter: string;
        timestamp: bigint;
        evidenceType: bigint;
        bondAmount: bigint;
        bondReturned: boolean;
      }
    ],
    "view"
  >;

  executeVerdict: TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;

  finalizeCommunityVote: TypedContractMethod<
    [qId: BytesLike],
    [void],
    "nonpayable"
  >;

  freezeQuestion: TypedContractMethod<
    [qId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getAIAnalysis: TypedContractMethod<
    [qId: BytesLike],
    [PlokyResolver.AIAnalysisStructOutput],
    "view"
  >;

  getAllIds: TypedContractMethod<[], [string[]], "view">;

  getDisputes: TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.DisputeStructOutput[]],
    "view"
  >;

  getEvidence: TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.EvidenceStructOutput[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [pid: BytesLike],
    [
      [bigint, string, bigint, bigint, string, bigint, boolean, bigint] & {
        outcome: bigint;
        proposer: string;
        proposedAt: bigint;
        timelockEndsAt: bigint;
        reasonCID: string;
        approvalCount: bigint;
        executed: boolean;
        totalWeight: bigint;
      }
    ],
    "view"
  >;

  getProposalWeight: TypedContractMethod<[pid: BytesLike], [bigint], "view">;

  getQuestion: TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.QuestionStructOutput],
    "view"
  >;

  getResolver: TypedContractMethod<
    [r: AddressLike],
    [PlokyResolver.ResolverProfileStructOutput],
    "view"
  >;

  getResolverWeight: TypedContractMethod<
    [resolver: AddressLike],
    [bigint],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasApproved: TypedContractMethod<
    [pid: BytesLike, r: AddressLike],
    [boolean],
    "view"
  >;

  hasDisputed: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  paused: TypedContractMethod<[], [boolean], "view">;

  plkyToken: TypedContractMethod<[], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, string, bigint, boolean, bigint] & {
        outcome: bigint;
        proposer: string;
        proposedAt: bigint;
        timelockEndsAt: bigint;
        reasonCID: string;
        approvalCount: bigint;
        executed: boolean;
        totalWeight: bigint;
      }
    ],
    "view"
  >;

  proposeVerdict: TypedContractMethod<
    [qId: BytesLike, outcome: BigNumberish, reasonCID: string, summary: string],
    [void],
    "nonpayable"
  >;

  questions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        title: string;
        descriptionCID: string;
        category: string;
        createdAt: bigint;
        deadline: bigint;
        creator: string;
        status: bigint;
        outcome: bigint;
        verdictCID: string;
        verdictSummary: string;
        resolvedAt: bigint;
        resolvedBy: string;
        disputeCount: bigint;
        frozen: boolean;
        activeProposalId: string;
        tier: bigint;
        currentStep: bigint;
        aiConfidenceScore: bigint;
        aiAnalysisCID: string;
      }
    ],
    "view"
  >;

  quorumThreshold: TypedContractMethod<[], [bigint], "view">;

  raiseDispute: TypedContractMethod<
    [qId: BytesLike, reason: string, evidCID: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  requestUMAResolution: TypedContractMethod<
    [qId: BytesLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [qId: BytesLike, idx: BigNumberish, res: string, validDispute: boolean],
    [void],
    "nonpayable"
  >;

  resolverCount: TypedContractMethod<[], [bigint], "view">;

  resolverList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  resolvers: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        reputationScore: bigint;
        totalResolved: bigint;
        correctResolutions: bigint;
        stakedAmount: bigint;
        slashCount: bigint;
        isActive: boolean;
        joinTimestamp: bigint;
        lastActivityTimestamp: bigint;
      }
    ],
    "view"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setAIThreshold: TypedContractMethod<
    [threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  setQuorum: TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  settleUMAResolution: TypedContractMethod<
    [qId: BytesLike],
    [void],
    "nonpayable"
  >;

  slashResolver: TypedContractMethod<
    [resolver: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;

  stakeAsResolver: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitAIAnalysis: TypedContractMethod<
    [
      qId: BytesLike,
      confidenceScore: BigNumberish,
      recommendedOutcome: BigNumberish,
      analysisCID: string,
      sentimentScore: BigNumberish,
      factCheckScore: BigNumberish,
      biasScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitEvidence: TypedContractMethod<
    [
      qId: BytesLike,
      ipfsCID: string,
      description: string,
      evidType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  totalQuestions: TypedContractMethod<[], [bigint], "view">;

  treasury: TypedContractMethod<[], [string], "view">;

  umaEnabled: TypedContractMethod<[], [boolean], "view">;

  umaOracle: TypedContractMethod<[], [string], "view">;

  unfreezeQuestion: TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;

  unstakeAsResolver: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawStuckTokens: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AI_ORACLE_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ARBITER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "AUTO_FREEZE_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DISPUTE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EVIDENCE_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_REPUTATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_EVIDENCE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_RESOLVER_STAKE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "RESOLVER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SLASH_PENALTY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERDICT_BOND"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "YES_OR_NO_IDENTIFIER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aiAnalyses"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        bigint,
        bigint,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        questionId: string;
        confidenceScore: bigint;
        recommendedOutcome: bigint;
        analysisCID: string;
        timestamp: bigint;
        aiModelVersion: string;
        sentimentScore: bigint;
        factCheckScore: bigint;
        biasScore: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "aiConfidenceThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approveVerdict"
  ): TypedContractMethod<
    [qId: BytesLike, pid: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelQuestion"
  ): TypedContractMethod<
    [qId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "castCommunityVote"
  ): TypedContractMethod<
    [qId: BytesLike, vote: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "communityVotes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createQuestion"
  ): TypedContractMethod<
    [
      title: string,
      descCID: string,
      category: string,
      deadline: BigNumberish,
      tier: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputes"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        boolean,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        questionId: string;
        disputer: string;
        reason: string;
        evidenceCID: string;
        timestamp: bigint;
        resolved: boolean;
        resolution: string;
        bondAmount: bigint;
        bondReturned: boolean;
        disputeIndex: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyPause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyUnpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableUMA"
  ): TypedContractMethod<[oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "evidence"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        ipfsCID: string;
        description: string;
        submitter: string;
        timestamp: bigint;
        evidenceType: bigint;
        bondAmount: bigint;
        bondReturned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeVerdict"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeCommunityVote"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "freezeQuestion"
  ): TypedContractMethod<
    [qId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAIAnalysis"
  ): TypedContractMethod<
    [qId: BytesLike],
    [PlokyResolver.AIAnalysisStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getDisputes"
  ): TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.DisputeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEvidence"
  ): TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.EvidenceStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [pid: BytesLike],
    [
      [bigint, string, bigint, bigint, string, bigint, boolean, bigint] & {
        outcome: bigint;
        proposer: string;
        proposedAt: bigint;
        timelockEndsAt: bigint;
        reasonCID: string;
        approvalCount: bigint;
        executed: boolean;
        totalWeight: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalWeight"
  ): TypedContractMethod<[pid: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuestion"
  ): TypedContractMethod<
    [id: BytesLike],
    [PlokyResolver.QuestionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolver"
  ): TypedContractMethod<
    [r: AddressLike],
    [PlokyResolver.ResolverProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getResolverWeight"
  ): TypedContractMethod<[resolver: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasApproved"
  ): TypedContractMethod<[pid: BytesLike, r: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "hasDisputed"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "plkyToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, string, bigint, bigint, string, bigint, boolean, bigint] & {
        outcome: bigint;
        proposer: string;
        proposedAt: bigint;
        timelockEndsAt: bigint;
        reasonCID: string;
        approvalCount: bigint;
        executed: boolean;
        totalWeight: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeVerdict"
  ): TypedContractMethod<
    [qId: BytesLike, outcome: BigNumberish, reasonCID: string, summary: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "questions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        bigint,
        boolean,
        string,
        bigint,
        bigint,
        bigint,
        string
      ] & {
        id: string;
        title: string;
        descriptionCID: string;
        category: string;
        createdAt: bigint;
        deadline: bigint;
        creator: string;
        status: bigint;
        outcome: bigint;
        verdictCID: string;
        verdictSummary: string;
        resolvedAt: bigint;
        resolvedBy: string;
        disputeCount: bigint;
        frozen: boolean;
        activeProposalId: string;
        tier: bigint;
        currentStep: bigint;
        aiConfidenceScore: bigint;
        aiAnalysisCID: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quorumThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<
    [qId: BytesLike, reason: string, evidCID: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUMAResolution"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<
    [qId: BytesLike, idx: BigNumberish, res: string, validDispute: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolverCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "resolverList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "resolvers"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, boolean, bigint, bigint] & {
        reputationScore: bigint;
        totalResolved: bigint;
        correctResolutions: bigint;
        stakedAmount: bigint;
        slashCount: bigint;
        isActive: boolean;
        joinTimestamp: bigint;
        lastActivityTimestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAIThreshold"
  ): TypedContractMethod<[threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuorum"
  ): TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleUMAResolution"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "slashResolver"
  ): TypedContractMethod<
    [resolver: AddressLike, amount: BigNumberish, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeAsResolver"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitAIAnalysis"
  ): TypedContractMethod<
    [
      qId: BytesLike,
      confidenceScore: BigNumberish,
      recommendedOutcome: BigNumberish,
      analysisCID: string,
      sentimentScore: BigNumberish,
      factCheckScore: BigNumberish,
      biasScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitEvidence"
  ): TypedContractMethod<
    [
      qId: BytesLike,
      ipfsCID: string,
      description: string,
      evidType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "totalQuestions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "umaEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "umaOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unfreezeQuestion"
  ): TypedContractMethod<[qId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeAsResolver"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawStuckTokens"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AIAnalysisSubmitted"
  ): TypedContractEvent<
    AIAnalysisSubmittedEvent.InputTuple,
    AIAnalysisSubmittedEvent.OutputTuple,
    AIAnalysisSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "BondReturned"
  ): TypedContractEvent<
    BondReturnedEvent.InputTuple,
    BondReturnedEvent.OutputTuple,
    BondReturnedEvent.OutputObject
  >;
  getEvent(
    key: "BondSeized"
  ): TypedContractEvent<
    BondSeizedEvent.InputTuple,
    BondSeizedEvent.OutputTuple,
    BondSeizedEvent.OutputObject
  >;
  getEvent(
    key: "CommunityVoteFinalized"
  ): TypedContractEvent<
    CommunityVoteFinalizedEvent.InputTuple,
    CommunityVoteFinalizedEvent.OutputTuple,
    CommunityVoteFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "CommunityVoted"
  ): TypedContractEvent<
    CommunityVotedEvent.InputTuple,
    CommunityVotedEvent.OutputTuple,
    CommunityVotedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeRaised"
  ): TypedContractEvent<
    DisputeRaisedEvent.InputTuple,
    DisputeRaisedEvent.OutputTuple,
    DisputeRaisedEvent.OutputObject
  >;
  getEvent(
    key: "DisputeResolved"
  ): TypedContractEvent<
    DisputeResolvedEvent.InputTuple,
    DisputeResolvedEvent.OutputTuple,
    DisputeResolvedEvent.OutputObject
  >;
  getEvent(
    key: "EscalationAdvanced"
  ): TypedContractEvent<
    EscalationAdvancedEvent.InputTuple,
    EscalationAdvancedEvent.OutputTuple,
    EscalationAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "EvidenceSubmitted"
  ): TypedContractEvent<
    EvidenceSubmittedEvent.InputTuple,
    EvidenceSubmittedEvent.OutputTuple,
    EvidenceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "QuestionCancelled"
  ): TypedContractEvent<
    QuestionCancelledEvent.InputTuple,
    QuestionCancelledEvent.OutputTuple,
    QuestionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "QuestionCreated"
  ): TypedContractEvent<
    QuestionCreatedEvent.InputTuple,
    QuestionCreatedEvent.OutputTuple,
    QuestionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "QuestionFrozen"
  ): TypedContractEvent<
    QuestionFrozenEvent.InputTuple,
    QuestionFrozenEvent.OutputTuple,
    QuestionFrozenEvent.OutputObject
  >;
  getEvent(
    key: "QuestionUnfrozen"
  ): TypedContractEvent<
    QuestionUnfrozenEvent.InputTuple,
    QuestionUnfrozenEvent.OutputTuple,
    QuestionUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "QuorumChanged"
  ): TypedContractEvent<
    QuorumChangedEvent.InputTuple,
    QuorumChangedEvent.OutputTuple,
    QuorumChangedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverAdded"
  ): TypedContractEvent<
    ResolverAddedEvent.InputTuple,
    ResolverAddedEvent.OutputTuple,
    ResolverAddedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverRemoved"
  ): TypedContractEvent<
    ResolverRemovedEvent.InputTuple,
    ResolverRemovedEvent.OutputTuple,
    ResolverRemovedEvent.OutputObject
  >;
  getEvent(
    key: "ResolverSlashed"
  ): TypedContractEvent<
    ResolverSlashedEvent.InputTuple,
    ResolverSlashedEvent.OutputTuple,
    ResolverSlashedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "UMAEnabled"
  ): TypedContractEvent<
    UMAEnabledEvent.InputTuple,
    UMAEnabledEvent.OutputTuple,
    UMAEnabledEvent.OutputObject
  >;
  getEvent(
    key: "UMARequested"
  ): TypedContractEvent<
    UMARequestedEvent.InputTuple,
    UMARequestedEvent.OutputTuple,
    UMARequestedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictApproved"
  ): TypedContractEvent<
    VerdictApprovedEvent.InputTuple,
    VerdictApprovedEvent.OutputTuple,
    VerdictApprovedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictExecuted"
  ): TypedContractEvent<
    VerdictExecutedEvent.InputTuple,
    VerdictExecutedEvent.OutputTuple,
    VerdictExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VerdictProposed"
  ): TypedContractEvent<
    VerdictProposedEvent.InputTuple,
    VerdictProposedEvent.OutputTuple,
    VerdictProposedEvent.OutputObject
  >;

  filters: {
    "AIAnalysisSubmitted(bytes32,uint256,uint8,string)": TypedContractEvent<
      AIAnalysisSubmittedEvent.InputTuple,
      AIAnalysisSubmittedEvent.OutputTuple,
      AIAnalysisSubmittedEvent.OutputObject
    >;
    AIAnalysisSubmitted: TypedContractEvent<
      AIAnalysisSubmittedEvent.InputTuple,
      AIAnalysisSubmittedEvent.OutputTuple,
      AIAnalysisSubmittedEvent.OutputObject
    >;

    "BondReturned(address,uint256,string)": TypedContractEvent<
      BondReturnedEvent.InputTuple,
      BondReturnedEvent.OutputTuple,
      BondReturnedEvent.OutputObject
    >;
    BondReturned: TypedContractEvent<
      BondReturnedEvent.InputTuple,
      BondReturnedEvent.OutputTuple,
      BondReturnedEvent.OutputObject
    >;

    "BondSeized(address,uint256,string)": TypedContractEvent<
      BondSeizedEvent.InputTuple,
      BondSeizedEvent.OutputTuple,
      BondSeizedEvent.OutputObject
    >;
    BondSeized: TypedContractEvent<
      BondSeizedEvent.InputTuple,
      BondSeizedEvent.OutputTuple,
      BondSeizedEvent.OutputObject
    >;

    "CommunityVoteFinalized(bytes32,uint8,uint256,uint256)": TypedContractEvent<
      CommunityVoteFinalizedEvent.InputTuple,
      CommunityVoteFinalizedEvent.OutputTuple,
      CommunityVoteFinalizedEvent.OutputObject
    >;
    CommunityVoteFinalized: TypedContractEvent<
      CommunityVoteFinalizedEvent.InputTuple,
      CommunityVoteFinalizedEvent.OutputTuple,
      CommunityVoteFinalizedEvent.OutputObject
    >;

    "CommunityVoted(bytes32,address,uint256,uint8)": TypedContractEvent<
      CommunityVotedEvent.InputTuple,
      CommunityVotedEvent.OutputTuple,
      CommunityVotedEvent.OutputObject
    >;
    CommunityVoted: TypedContractEvent<
      CommunityVotedEvent.InputTuple,
      CommunityVotedEvent.OutputTuple,
      CommunityVotedEvent.OutputObject
    >;

    "DisputeRaised(bytes32,address,string,string,uint256)": TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;
    DisputeRaised: TypedContractEvent<
      DisputeRaisedEvent.InputTuple,
      DisputeRaisedEvent.OutputTuple,
      DisputeRaisedEvent.OutputObject
    >;

    "DisputeResolved(bytes32,uint256,string,bool)": TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;
    DisputeResolved: TypedContractEvent<
      DisputeResolvedEvent.InputTuple,
      DisputeResolvedEvent.OutputTuple,
      DisputeResolvedEvent.OutputObject
    >;

    "EscalationAdvanced(bytes32,uint8,uint8)": TypedContractEvent<
      EscalationAdvancedEvent.InputTuple,
      EscalationAdvancedEvent.OutputTuple,
      EscalationAdvancedEvent.OutputObject
    >;
    EscalationAdvanced: TypedContractEvent<
      EscalationAdvancedEvent.InputTuple,
      EscalationAdvancedEvent.OutputTuple,
      EscalationAdvancedEvent.OutputObject
    >;

    "EvidenceSubmitted(bytes32,address,string,uint8,uint256)": TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;
    EvidenceSubmitted: TypedContractEvent<
      EvidenceSubmittedEvent.InputTuple,
      EvidenceSubmittedEvent.OutputTuple,
      EvidenceSubmittedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "QuestionCancelled(bytes32,string)": TypedContractEvent<
      QuestionCancelledEvent.InputTuple,
      QuestionCancelledEvent.OutputTuple,
      QuestionCancelledEvent.OutputObject
    >;
    QuestionCancelled: TypedContractEvent<
      QuestionCancelledEvent.InputTuple,
      QuestionCancelledEvent.OutputTuple,
      QuestionCancelledEvent.OutputObject
    >;

    "QuestionCreated(bytes32,string,address,uint256,string,uint8)": TypedContractEvent<
      QuestionCreatedEvent.InputTuple,
      QuestionCreatedEvent.OutputTuple,
      QuestionCreatedEvent.OutputObject
    >;
    QuestionCreated: TypedContractEvent<
      QuestionCreatedEvent.InputTuple,
      QuestionCreatedEvent.OutputTuple,
      QuestionCreatedEvent.OutputObject
    >;

    "QuestionFrozen(bytes32,address,string)": TypedContractEvent<
      QuestionFrozenEvent.InputTuple,
      QuestionFrozenEvent.OutputTuple,
      QuestionFrozenEvent.OutputObject
    >;
    QuestionFrozen: TypedContractEvent<
      QuestionFrozenEvent.InputTuple,
      QuestionFrozenEvent.OutputTuple,
      QuestionFrozenEvent.OutputObject
    >;

    "QuestionUnfrozen(bytes32,address)": TypedContractEvent<
      QuestionUnfrozenEvent.InputTuple,
      QuestionUnfrozenEvent.OutputTuple,
      QuestionUnfrozenEvent.OutputObject
    >;
    QuestionUnfrozen: TypedContractEvent<
      QuestionUnfrozenEvent.InputTuple,
      QuestionUnfrozenEvent.OutputTuple,
      QuestionUnfrozenEvent.OutputObject
    >;

    "QuorumChanged(uint256,uint256,address)": TypedContractEvent<
      QuorumChangedEvent.InputTuple,
      QuorumChangedEvent.OutputTuple,
      QuorumChangedEvent.OutputObject
    >;
    QuorumChanged: TypedContractEvent<
      QuorumChangedEvent.InputTuple,
      QuorumChangedEvent.OutputTuple,
      QuorumChangedEvent.OutputObject
    >;

    "ResolverAdded(address,uint256,address)": TypedContractEvent<
      ResolverAddedEvent.InputTuple,
      ResolverAddedEvent.OutputTuple,
      ResolverAddedEvent.OutputObject
    >;
    ResolverAdded: TypedContractEvent<
      ResolverAddedEvent.InputTuple,
      ResolverAddedEvent.OutputTuple,
      ResolverAddedEvent.OutputObject
    >;

    "ResolverRemoved(address,address)": TypedContractEvent<
      ResolverRemovedEvent.InputTuple,
      ResolverRemovedEvent.OutputTuple,
      ResolverRemovedEvent.OutputObject
    >;
    ResolverRemoved: TypedContractEvent<
      ResolverRemovedEvent.InputTuple,
      ResolverRemovedEvent.OutputTuple,
      ResolverRemovedEvent.OutputObject
    >;

    "ResolverSlashed(address,uint256,string)": TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;
    ResolverSlashed: TypedContractEvent<
      ResolverSlashedEvent.InputTuple,
      ResolverSlashedEvent.OutputTuple,
      ResolverSlashedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "UMAEnabled(address)": TypedContractEvent<
      UMAEnabledEvent.InputTuple,
      UMAEnabledEvent.OutputTuple,
      UMAEnabledEvent.OutputObject
    >;
    UMAEnabled: TypedContractEvent<
      UMAEnabledEvent.InputTuple,
      UMAEnabledEvent.OutputTuple,
      UMAEnabledEvent.OutputObject
    >;

    "UMARequested(bytes32,bytes32,uint256)": TypedContractEvent<
      UMARequestedEvent.InputTuple,
      UMARequestedEvent.OutputTuple,
      UMARequestedEvent.OutputObject
    >;
    UMARequested: TypedContractEvent<
      UMARequestedEvent.InputTuple,
      UMARequestedEvent.OutputTuple,
      UMARequestedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VerdictApproved(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      VerdictApprovedEvent.InputTuple,
      VerdictApprovedEvent.OutputTuple,
      VerdictApprovedEvent.OutputObject
    >;
    VerdictApproved: TypedContractEvent<
      VerdictApprovedEvent.InputTuple,
      VerdictApprovedEvent.OutputTuple,
      VerdictApprovedEvent.OutputObject
    >;

    "VerdictExecuted(bytes32,uint8,string,address,uint256)": TypedContractEvent<
      VerdictExecutedEvent.InputTuple,
      VerdictExecutedEvent.OutputTuple,
      VerdictExecutedEvent.OutputObject
    >;
    VerdictExecuted: TypedContractEvent<
      VerdictExecutedEvent.InputTuple,
      VerdictExecutedEvent.OutputTuple,
      VerdictExecutedEvent.OutputObject
    >;

    "VerdictProposed(bytes32,bytes32,uint8,address,string,uint256)": TypedContractEvent<
      VerdictProposedEvent.InputTuple,
      VerdictProposedEvent.OutputTuple,
      VerdictProposedEvent.OutputObject
    >;
    VerdictProposed: TypedContractEvent<
      VerdictProposedEvent.InputTuple,
      VerdictProposedEvent.OutputTuple,
      VerdictProposedEvent.OutputObject
    >;
  };
}
