#!/bin/bash
# PLOKY SIMULATOR — CX33 VPS DEPLOYMENT SCRIPT
# Usage: ./deploy-simulator.sh <supabase_url> <service_role_key>

set -e

SUPABASE_URL="${1:-$SUPABASE_URL}"
SERVICE_KEY="${2:-$SUPABASE_SERVICE_ROLE_KEY}"

if [ -z "$SUPABASE_URL" ] || [ -z "$SERVICE_KEY" ]; then
  echo "Usage: ./deploy-simulator.sh <SUPABASE_URL> <SERVICE_ROLE_KEY>"
  echo ""
  echo "Example (self-hosted):"
  echo "  ./deploy-simulator.sh http://localhost:8000 eyJhbG..."
  echo ""
  echo "Example (Supabase Cloud):"
  echo "  ./deploy-simulator.sh https://abcdefgh12345678.supabase.co eyJhbG..."
  exit 1
fi

echo "🚀 Deploying Ploky Simulator to cx33..."

# 1. Ensure we're in the simulator directory
SIM_DIR="/opt/plokymarket/apps/web/scripts/simulator"
if [ ! -d "$SIM_DIR" ]; then
  echo "❌ Simulator directory not found at $SIM_DIR"
  echo "   Make sure the repo is cloned at /opt/plokymarket"
  exit 1
fi

cd "$SIM_DIR"

# 2. Install dependencies if needed
if [ ! -d "node_modules" ]; then
  echo "📦 Installing dependencies..."
  npm install
fi

# 3. Write .env.simulator (gitignored, never committed)
cat > .env.simulator <<EOF
# Auto-generated by deploy-simulator.sh — DO NOT COMMIT
SUPABASE_URL=$SUPABASE_URL
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY
SIMULATION_DURATION_MINUTES=1
USER_COUNT=5
INITIAL_BALANCE=1000
ENABLE_STRESS_TEST=true
LOG_TO_FILE=true
EOF

echo "🔑 Environment written to .env.simulator"

# 4. Run pre-flight check
echo ""
echo "🔍 Running pre-flight connectivity check..."
export SUPABASE_URL="$SUPABASE_URL"
export SUPABASE_SERVICE_ROLE_KEY="$SERVICE_KEY"
npx tsx preflight-check.ts

# 5. Run fast simulation
echo ""
echo "🏁 Starting FAST simulation (1 minute, 5 users)..."
npx tsx ploky-simulator.ts

echo ""
echo "✅ Simulation complete. Check simulation-report-*.json for full audit."
